command:
  sender:
    properties:
      control_respond_timeout_seconds: 3
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource  #com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://120.26.128.16:3306/potion_sorting?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/vaccine_dispenser?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: ydkj.zxcvb123
    password: root
    hikari:
      maximum-pool-size: 100
      max-lifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 10
    timeout: 5000
    jedis:
      pool:
        max-wait: 2000
        min-idle: 2
        max-idle: 8
        max-active: 8
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
logging:
  level:
    com.yiwan.vaccinedispenser.system.sys.dao: warn #mapper的路径 mapper增加日志等级为debug
    root: info

## netty相关的配置
netty:
  ## (控制A、B柜子)是否启用netty_client服务，true表示启用。false禁用所有
  enable: true
